// Generate ts/src/kko-data.ts (the embedded KKO ontology the engine ships) from the vendored
// ontology/kko/kko-2.10.n3, using the engine's own parseKko. Run via tsx:
//   node --import tsx scripts/gen-kko.mjs
// Commit both the .n3 and the regenerated kko-data.ts after re-vendoring a newer KKO.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { parseKko } from '../ts/src/kko.ts'

const n3Path = fileURLToPath(new URL('../ontology/kko/kko-2.10.n3', import.meta.url))
const outPath = fileURLToPath(new URL('../ts/src/kko-data.ts', import.meta.url))

const onto = parseKko(readFileSync(n3Path, 'utf8'))
onto.classes.sort((a, b) => a.iri.localeCompare(b.iri)) // deterministic output

const rows = onto.classes
  .map((c) => {
    const label = c.label !== undefined ? `, label: ${JSON.stringify(c.label)}` : ''
    return `  { iri: ${JSON.stringify(c.iri)}${label}, subClassOf: ${JSON.stringify(c.subClassOf)} },`
  })
  .join('\n')

const out = `// GENERATED by scripts/gen-kko.mjs from ontology/kko/kko-2.10.n3 — do not edit by hand.
// KKO ${onto.version} · ${onto.classes.length} classes. Regenerate after re-vendoring KKO.
import type { KkoClass } from './kko'

export const KKO_VERSION = ${JSON.stringify(onto.version)}
export const KKO_CLASSES: KkoClass[] = [
${rows}
]
`

writeFileSync(outPath, out)
console.log(`wrote ${onto.classes.length} KKO classes (${onto.version}) → ts/src/kko-data.ts`)
